# Generated by Django 3.2.2 on 2021-05-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motion',
            name='date_limit',
        ),
    ]
