# Generated by Django 3.2.2 on 2021-05-19 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debate', '0002_remove_motion_date_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('PROP', 'Proposition'), ('OPP', 'Opposition')], max_length=4)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('to_motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.motion')),
            ],
        ),
    ]
