# Generated by Django 3.2.2 on 2021-05-20 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debate', '0003_auto_20210519_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='subpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('PROP', 'Proposition'), ('OPP', 'Opposition')], max_length=4)),
                ('content', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('to_arg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.argument')),
            ],
        ),
    ]
