# Generated by Django 3.2.2 on 2021-05-20 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0004_auto_20210520_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpoint',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
